env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - eslint-config-prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  no-console: 'off'
  import/extensions: 'off'
  react/react-in-jsx-scope: 'off'
settings:
  react:
    version: 'detect'
ignorePatterns:
  - 'dist/'
  - vite.config.ts
